# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Manual pipeline 

on:
  workflow_dispatch:

jobs:
  generate_and_send_digest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install msmtp
      run: sudo apt-get install msmtp
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate Digest 
      run: |
        python src/action.py --config cs_config.yaml,stats_config.yaml
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: digest.html
        path: digest.html
    - name: Configure msmtp
      run: |
        echo "account default" > ~/.msmtprc
        echo "host smtp.gmail.com" >> ~/.msmtprc
        echo "port 587" >> ~/.msmtprc
        echo "from ${{ secrets.GMAIL_ADDRESS }}" >> ~/.msmtprc
        echo "auth on" >> ~/.msmtprc
        echo "user ${{ secrets.GMAIL_ADDRESS }}" >> ~/.msmtprc
        echo "password ${{ secrets.GMAIL_APP_PASSWORD }}" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        chmod 600 ~/.msmtprc
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        ls -la

        # Rename the digest to have a timestamp
        timestamp=$(date +"%Y-%m-%d--%H-%M-%S")
        mkdir digest
        cp digest.html digest/digest_${timestamp}.html

        git add digest/digest_${timestamp}.html
        git commit -m "Add digest for ${timestamp}"
        git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Send email
      run: |
        ls -la

        timestamp=$(date +"%Y-%m-%d")
        SUBJECT="ML Papers Email Report ${timestamp}"
        TO="${{ secrets.GMAIL_ADDRESS }}"
        BODY=$(<digest.html)
        { echo "To: $TO"; echo "Subject: $SUBJECT"; echo "MIME-Version: 1.0"; echo "Content-Type: text/html"; echo; echo "$BODY"; } | msmtp -t $TO